@startuml TransitionWorkflow
start

-> Event received;

if (Internal transition triggered?) then (yes)
     :Execute internal transition;
elseif (State transition triggered?) then (yes)
     :Execute state transition;
elseif (State has a default transition?) then (yes)
     :Execute default transition;
else (no)
endif

stop
@enduml

'---------------------------------------------------------------------------------------------------

@startuml StateTransitionWorkflow
start

-> State transition triggered;

if (Transition has guard condition?) then (yes)
     if (Guard condition satisfied?) then (no)
          stop
     else (yes)
     endif
else (no)
endif

if (Current state has exit action?) then (yes)
     :Execute current state's exit action;
else (no)
endif

if (Transition has action?) then (yes)
     :Execute transition's action;
else (no)
endif

if (Next state has entry action?) then (yes)
     :Execute next state's entry action;
else (no)
endif

:Set next state as current state;

stop
@enduml

'---------------------------------------------------------------------------------------------------

@startuml InternalTransitionWorkflow
start

-> Internal transition triggered;

if (Transition has guard condition?) then (yes)
     if (Guard condition satisfied?) then (no)
          stop
     else (yes)
     endif
else (no)
endif

:Execute transition's action;

stop
@enduml

'---------------------------------------------------------------------------------------------------

@startuml DefaultTransitionWorkflow
start

-> Default transition triggered;

if (Transition has guard condition?) then (yes)
     if (Guard condition satisfied?) then (no)
          stop
     else (yes)
     endif
else (no)
endif

:Execute transition's action;

stop
@enduml
